services:
  # runs the frontend
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      api:
        condition: service_started
      mqtt:
        condition: service_started
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=100"
    restart: unless-stopped

  # listens to mqtt packets and saves to database
  mqtt:
    container_name: mqtt
    build:
      context: .
      dockerfile: ./mqtt/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=100"
    restart: unless-stopped

  # runs the database to store everything from mqtt
  database:
    container_name: database
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: "meshtastic-map"
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_interval: 5s

  proxy:
    container_name: proxy
    image: nginx:alpine
    depends_on:
      app:
        condition: service_healthy
      api:
        condition: service_healthy
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test:
        ["CMD-SHELL", "wget -O- http://localhost/nginx/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
    restart: unless-stopped

volumes:
  database_data:
